##
## Copyright (c) 2015, Jozef Stefan Institute, Quintelligence d.o.o. and contributors
## All rights reserved.
## 
## This source code is licensed under the FreeBSD license found in the
## LICENSE file in the root directory of this source tree.
##

#
#	Global configuration for Glib makefiles
#

UNAME := $(shell uname)
GLIB_DIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
LIBUV_DIR := $(GLIB_DIR)../third_party/libuv/
SOLE_DIR := $(GLIB_DIR)../third_party/sole/

ifeq ($(UNAME), Linux)
  # Linux flags
  CC = g++
  # turn on for crash debugging, get symbols with <prog> 2>&1 | c++filt
  CXXFLAGS += -g -rdynamic -DMEMORYCHECK
  LDFLAGS += -fopenmp
  LIBS += -lrt

else ifeq ($(UNAME), Darwin)
  # OS X flags
  CC = clang

endif

CXXFLAGS += -std=c++11 -Wall -I$(GLIB_DIR)base -I$(GLIB_DIR)mine -I$(GLIB_DIR)net -I$(LIBUV_DIR)src -I$(SOLE_DIR)
CXXFLAGS += -O3
	
