#
# Global configuration for QMiner makefiles
#

UNAME := $(shell uname)

ifeq ($(UNAME), Linux)
  # Linux flags
  CC = g++
  CXXFLAGS += -std=c++0x -Wall -Wno-deprecated-declarations
  #CXXFLAGS += -O3
  # turn on for crash debugging, get symbols with <prog> 2>&1 | c++filt
  CXXFLAGS += -g -rdynamic
  LDFLAGS += -fopenmp
  LIBS += -lrt -luuid

else ifeq ($(UNAME), Darwin)
  # OS X flags
  CC = g++
  CXXFLAGS += -std=c++0x -Wall -Wno-deprecated-declarations
  CXXFLAGS += -O3
  LDFLAGS += -fopenmp
  LIBS += -lrt -luuid

else ifeq ($(shell uname -o), Cygwin)
  # Cygwin flags
  CC = g++
  CXXFLAGS += -std=c++0x -Wall -Wno-deprecated-declarations
  CXXFLAGS += -O3
  LDFLAGS += -fopenmp
  LIBS += -lrt -luuid

endif

#
#  Parameters for Doxygen
#

DOXYGEN_TIME := $(shell date +%Y%m%d-%H%M%S)
DOXYGEN_STIME := $(shell date +"%Y-%m-%d %H:%M:%S")
DOXYGEN_SLVER := $(VERSION)

DOXYGEN = doxygen
ifeq ($(shell uname), Darwin)
	# OS X values
	DOXYGEN = /Applications/Doxygen.app/Contents/Resources/doxygen
endif

