#
# Global configuration for QMiner makefiles
#

UNAME := $(shell uname)

ifeq ($(UNAME), Linux)
  # Linux flags
  CC = g++
  CXXFLAGS += -std=c++0x -Wall -Wno-deprecated-declarations
  LIBS += -fopenmp -lrt -luuid

else ifeq ($(UNAME), Darwin)
  # OS X flags
  CC = g++
  CXXFLAGS += -std=c++11 -Wall -Wno-deprecated-declarations
  LDFLAGS += -framework CoreFoundation -framework CoreServices

endif

#
#  Parameters for Doxygen
#

DOXYGEN_TIME := $(shell date +%Y%m%d-%H%M%S)
DOXYGEN_STIME := $(shell date +"%Y-%m-%d %H:%M:%S")
DOXYGEN_SLVER := $(VERSION)

DOXYGEN = doxygen
ifeq ($(shell uname), Darwin)
	# OS X values
	DOXYGEN = /Applications/Doxygen.app/Contents/Resources/doxygen
endif

