exports.view = {
    "title": "Vector - array of boolean",
    "className": "BoolVector",
    "elementType": "boolean",

    "example1": "[true, true, false]",
    "input1": "false, true",
    "output1": "'[true, true, false]'",
    "output2": "[true, false, true]",
    "output3": "[true]",

    "skipInner": "skip.",
    "skipSum": "skip.",
    "skipGetMaxIdx": "skip.",
    "skipSort": "skip.",
    "skipOuter": "skip.",
    "skipInner": "skip.",
    "skipCosine": "skip.",
    "skipPlus": "skip.",
    "skipMinus": "skip.",
    "skipMultiply": "skip.",
    "skipNormalize": "skip.",
    "skipDiag": "skip.",
    "skipSpDiag": "skip.",
    "skipNorm": "skip.",
    "skipSparse": "skip.",
    "skipToMat": "skip.",
    "skipSave": "",
    "skipLoad": "",
}
