exports.view = {
    "title": "Vector - array of integers",
    "className": "IntVector",
    "elementType": "number",

    "example1": "[1, 2, 3]",
    "input1": "4, 5",
    "output1": "'[1, 2, 3]'",
    "output2": "[1, 4, 5]",
    "output3": "[1]",

    "skipInner": "skip.",
    "skipSum": "",
    "skipGetMaxIdx": "",
    "skipSort": "",
    "skipOuter": "skip.",
    "skipInner": "skip.",
    "skipCosine": "skip.",
    "skipPlus": "skip.",
    "skipMinus": "skip.",
    "skipMultiply": "skip.",
    "skipNormalize": "skip.",
    "skipDiag": "skip.",
    "skipSpDiag": "skip.",
    "skipNorm": "skip.",
    "skipSparse": "skip.",
    "skipToMat": "skip.",
    "skipSave": "",
    "skipLoad": "",
}