exports.view = {
	"title" : "Vector - array of strings",
	"className" : "StrVector",
	"elementType": "string",

	"example1": "['a', 'b', 'c']",
    "input1": "'d', 'e'",
    "output1": "'[a, b, c]'",
    "output2": "['a', 'd', 'e']",
    "output3": "['a']",

	"skipInner": "skip.",
	"skipSum": "skip.",
	"skipGetMaxIdx": "skip.",
	"skipSort": "skip.",
	"skipOuter": "skip.",
	"skipInner": "skip.",
	"skipCosine": "skip.",
	"skipPlus": "skip.",
	"skipMinus": "skip.",
	"skipMultiply": "skip.",
	"skipNormalize": "skip.",
	"skipDiag": "skip.",
	"skipSpDiag": "skip.",
	"skipNorm": "skip.",
	"skipSparse": "skip.",
	"skipToMat": "skip.",
	"skipSave": "",
    "skipLoad": "",
}