exports.view = {
	"title" : "Vector - array of doubles",
	"className" : "Vector",
	"elementType": "number",

	"example1": "[1, 2, 3]",
	"output1": "'[1, 2, 3]'",

	"skipInner": "",
	"skipSum": "",
	"skipGetMaxIdx": "",
	"skipSort": "",
	"skipOuter": "",
	"skipInner": "",
	"skipCosine": "",
	"skipPlus": "",
	"skipMinus": "",
	"skipMultiply": "",
	"skipNormalize": "",
	"skipDiag": "",
	"skipSpDiag": "",
	"skipNorm": "",
	"skipSparse": "",
	"skipToMat": "",
	"skipSave": "",
    "skipLoad": "",
}