##
## Copyright (c) 2015, Jozef Stefan Institute, Quintelligence d.o.o. and contributors
## All rights reserved.
## 
## This source code is licensed under the FreeBSD license found in the
## LICENSE file in the root directory of this source tree.
##
#
# Makefile for Debian derivatives (including Ubuntu)
# 	tested only on Ubuntu trusty
#
# Prerequisites:
#	- install package libgtest-dev
#
# Compile and run all the tests:
#	make run
#

# glib
GLIB = ../../src/glib
include $(GLIB)/Makefile.config

# gtest
GTEST = /usr/src/gtest
GTEST_SRCS = \
	gtest-all.cc
CXXFLAGS += -I$(GTEST)
VPATH += $(GTEST)/src

## Main application file
MAIN = run-all-tests

TEST_SRCS = \
	test-TStr.cpp \
	test-THash.cpp \
	test-zipfl.cpp

TEST_OBJS = $(TEST_SRCS:.cpp=.o) $(GTEST_SRCS:.cc=.o)

# we test in release	
CXXFLAGS += -O3 -DNDEBUG

.PHONY: all run
all: $(MAIN)
run: test

# COMPILE
.cc.o .cpp.o:
	$(CC) $(CXXFLAGS) -c $<

$(MAIN): $(MAIN).o $(TEST_OBJS) $(GLIB)/glib.a
	$(CC) -o $(MAIN) $^ $(LDFLAGS) $(LIBS)

.PHONY: $(GLIB)/glib.a
$(GLIB)/glib.a:
	$(MAKE) -C $(GLIB) release

.PHONY: test
test: $(MAIN)
	./$(MAIN)

.PHONY: clean
clean:
	$(MAKE) -C $(GLIB) clean
	rm -f *.o $(MAIN)
	rm -rf test*.dat *.Err
